# 04. TensorFlow 框架介紹

## 目錄

- 基礎用法
- 將 Tensor 轉換為 Numpy
- TensorFlow 運算方法
- 變數


## 基礎用法

### 匯入套件庫

In [18]:
# 安裝 TensorFlow 套件
!pip install tensorflow

In [19]:
# 匯入 TensorFlow 套件
import tensorflow as tf
print("TensorFlow 版本:", tf.__version__)

TensorFlow 版本: 2.13.0


### 基本用法

#### 創建張量 (Tensor)

##### 創建 rank 0 張量 (純量, Scalar)

In [20]:
rank_0_tensor = tf.constant(4)

print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


##### 創建 rank 1 張量 (向量, Vector)

In [21]:
rank_1_tensor = tf.constant([2., 3., 4.])

print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


##### 創建 rank 2 張量 (矩陣, Matrix)

In [22]:
rank_2_tensor = tf.constant(
    [[1, 2],
     [3, 4],
     [5, 6]],
    dtype=tf.float16
)

print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


##### 創建更高維度的張量

創建 float32 例型的張量

In [23]:
rank_3_tensor = tf.constant([
  [[ 0,  1,  2,  3,  4],
   [ 5,  6,  7,  8,  9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]]])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


## 將 Tensor 轉換為 Numpy

### 匯入 Numpy 套件

In [24]:
import numpy as np

### 轉換成 Numpy

將 TensorFlow 轉換成 Numpy 有兩種方法，分別是利用 Numpy 提供的方法與使用 TensorFlow 本身的方法來達成。

#### 利用 Numpy 的方法

In [25]:
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

#### 利用 TensorFlow 的方法

In [26]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

## TensorFlow 運算方法

### 定義張量 a 與 b

In [30]:
a = tf.constant(
    [[1, 2],
     [3, 4]]
)

print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [29]:
b = tf.constant(
    [[1, 1],
     [1, 1]]
)

print(b)

tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


### 加法運算

In [31]:
tf.add(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [34]:
a + b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

### 元素乘法

In [32]:
tf.multiply(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [35]:
a * b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### 矩陣乘法

In [33]:
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]], dtype=int32)>

In [36]:
a @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]], dtype=int32)>

### 聚合運算

- tf.reduce_sum() : 求和
- tf.reduce_mean() : 平均值
- tf.reduce_max()  : 最大值
- tf.reduce_min()  : 最小值
- tf.argmax() : 最大值的索引
- tf.argmin() : 最小值的索引

#### 定義張量 c

In [39]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4.,  5.],
       [10.,  1.]], dtype=float32)>

#### 最大值

In [40]:
tf.reduce_max(c)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

#### 最大值索引

In [41]:
tf.argmax(c)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0])>

#### 均值

In [42]:
tf.reduce_mean(c)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

## 變數

In [43]:
var1 = tf.Variable([[1.0, 2.0], [3.0, 4.0]])
var1

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

## Keras 介紹

### 從 TensorFlow 匯入 Keras 套件

In [46]:
from tensorflow import keras

### 使用 Keras 載入 MNIST 資料集

載入資料集與正規化

In [51]:
mnist = keras.datasets.mnist

In [52]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

### 模型建構

#### 從 Keras 匯入 Layer 套件

In [53]:
from tensorflow.keras import layers as KL

#### 建置手寫辨識分類資料集

In [54]:
model = keras.models.Sequential([
    KL.Flatten(input_shape=(28, 28)),
    KL.Dense(128, activation='relu'),
    KL.Dropout(0.2),
    KL.Dense(10)
])

#### 模型預測

##### 對樣本進行預測

會回傳會是樣本對於每個類別的邏輯分數(Logits)向量。

In [57]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.6793607 , -0.1534846 ,  0.1577643 ,  0.1113722 , -0.2822224 ,
        -0.13211143, -0.01687551,  0.42131132, -0.15692118,  0.4346081 ]],
      dtype=float32)

##### 透過 Softmax 轉為每個類別的機率

In [59]:
tf.nn.softmax(predictions).numpy()

array([[0.04974858, 0.08417165, 0.11490515, 0.10969622, 0.07400408,
        0.08599002, 0.09649269, 0.14955348, 0.08388288, 0.15155533]],
      dtype=float32)

#### 計算損失函數

未經過訓練的模型，給出的機率值接近隨機(1/10)，因此初始損失應該接近

```
-tf.math.log(1/10) ~= 2.3
```

In [62]:
-tf.math.log(1/10)

<tf.Tensor: shape=(), dtype=float32, numpy=2.3025851>

##### 使用稀疏分類交叉熵

In [60]:
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [61]:
loss_fn(y_train[:1], predictions).numpy()

2.453524

#### 編譯模型

In [63]:
model.compile(
    optimizer='adam',
    loss=loss_fn,
    metrics=['accuracy']
)

#### 訓練並評估模型

##### 模型訓練

In [65]:
model.fit(
    x_train, y_train,
    epochs=5
)

Epoch 1/5
1875/1875 [==============================] - 9s 4ms/step - loss: 0.3013 - accuracy: 0.9125
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1464 - accuracy: 0.9560
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1105 - accuracy: 0.9669
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0904 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0777 - accuracy: 0.9750


##### 模型評估

In [66]:
model.evaluate(
    x_test, y_test,
    verbose=2
)

313/313 - 1s - loss: 0.0734 - accuracy: 0.9787 - 638ms/epoch - 2ms/step


[0.07344241440296173, 0.9786999821662903]

##### 建立機率模型

In [67]:
probability_model = keras.Sequential([
    model,
    KL.Softmax()
])

In [68]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.1696514e-08, 2.7458467e-09, 2.6161582e-05, 1.6867516e-04,
        1.5740411e-11, 1.3165561e-07, 2.7404797e-12, 9.9980396e-01,
        3.1159510e-07, 7.7086406e-07],
       [4.5801182e-11, 7.1181530e-06, 9.9999046e-01, 2.2891861e-06,
        9.2500444e-19, 1.3504530e-07, 4.5470567e-12, 3.7719136e-13,
        6.9872645e-09, 9.7171267e-14],
       [6.7541714e-07, 9.9609756e-01, 1.2857359e-03, 1.2525081e-04,
        2.4198753e-05, 1.1542739e-06, 1.0117909e-05, 2.3737724e-03,
        8.0676276e-05, 8.7986717e-07],
       [9.9996912e-01, 1.8453258e-10, 1.1222852e-05, 1.9621282e-08,
        1.4486550e-06, 4.7906661e-07, 9.1775828e-06, 7.6875574e-07,
        8.0741353e-07, 6.9900652e-06],
       [8.3209773e-07, 1.8021907e-09, 2.5909005e-06, 6.8342709e-09,
        9.9732876e-01, 1.9453289e-08, 4.0331778e-07, 4.7406531e-05,
        1.7372315e-08, 2.6200230e-03]], dtype=float32)>