# 04. TensorFlow 框架介紹

## 目錄

- 基礎用法
- 將 Tensor 轉換為 Numpy
- TensorFlow 運算方法
- 變數


## 基礎用法

### 匯入套件庫

In [1]:
# 安裝 TensorFlow 套件
!pip install tensorflow

In [2]:
# 匯入 TensorFlow 套件
import tensorflow as tf
print("TensorFlow 版本:", tf.__version__)

2023-10-23 18:41:57.065139: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-23 18:41:57.092292: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-23 18:41:57.092316: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-23 18:41:57.092346: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-23 18:41:57.097375: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-23 18:41:57.097803: I tensorflow/core/platform/cpu_feature_guard.cc:182] This Tens

TensorFlow 版本: 2.14.0


### 基本用法

#### 創建張量 (Tensor)

##### 創建 rank 0 張量 (純量, Scalar)

In [3]:
rank_0_tensor = tf.constant(4)

print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


2023-10-23 18:41:58.278921: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-23 18:41:58.279104: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-23 18:41:58.279424: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2211] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the 

##### 創建 rank 1 張量 (向量, Vector)

In [4]:
rank_1_tensor = tf.constant([2., 3., 4.])

print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


##### 創建 rank 2 張量 (矩陣, Matrix)

In [5]:
rank_2_tensor = tf.constant(
    [[1, 2],
     [3, 4],
     [5, 6]],
    dtype=tf.float16
)

print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


##### 創建更高維度的張量

創建 float32 例型的張量

In [6]:
rank_3_tensor = tf.constant([
  [[ 0,  1,  2,  3,  4],
   [ 5,  6,  7,  8,  9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]]])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


## 將 Tensor 轉換為 Numpy

### 匯入 Numpy 套件

In [7]:
import numpy as np

### 轉換成 Numpy

將 TensorFlow 轉換成 Numpy 有兩種方法，分別是利用 Numpy 提供的方法與使用 TensorFlow 本身的方法來達成。

#### 利用 Numpy 的方法

In [8]:
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

#### 利用 TensorFlow 的方法

In [9]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

## TensorFlow 運算方法

### 定義張量 a 與 b

In [10]:
a = tf.constant(
    [[1, 2],
     [3, 4]]
)

print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [11]:
b = tf.constant(
    [[1, 1],
     [1, 1]]
)

print(b)

tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


### 加法運算

In [12]:
tf.add(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [13]:
a + b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

### 元素乘法

In [14]:
tf.multiply(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [15]:
a * b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### 矩陣乘法

In [16]:
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]], dtype=int32)>

In [17]:
a @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]], dtype=int32)>

### 聚合運算

- tf.reduce_sum() : 求和
- tf.reduce_mean() : 平均值
- tf.reduce_max()  : 最大值
- tf.reduce_min()  : 最小值
- tf.argmax() : 最大值的索引
- tf.argmin() : 最小值的索引

#### 定義張量 c

In [18]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4.,  5.],
       [10.,  1.]], dtype=float32)>

#### 最大值

In [19]:
tf.reduce_max(c)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

#### 最大值索引

In [20]:
tf.argmax(c)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0])>

#### 均值

In [21]:
tf.reduce_mean(c)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

## 變數

In [22]:
var1 = tf.Variable([[1.0, 2.0], [3.0, 4.0]])
var1

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

## Keras 介紹

### 從 TensorFlow 匯入 Keras 套件

### 使用 Keras 載入 MNIST 資料集

載入資料集與正規化

### 模型建構

#### 從 Keras 匯入 Layer 套件

#### 建置手寫辨識分類資料集

#### 模型預測

##### 對樣本進行預測

會回傳會是樣本對於每個類別的邏輯分數(Logits)向量。

array([[-0.26944628, -0.33950424,  0.01807639,  0.26037255,  0.34969878,
         0.14384484,  0.54202366, -1.5258648 ,  0.04568738, -0.07889077]],
      dtype=float32)

##### 透過 Softmax 轉為每個類別的機率

array([[0.07435243, 0.06932172, 0.09912077, 0.12629685, 0.13809769,
        0.11240488, 0.16738327, 0.02116603, 0.10189572, 0.0899606 ]],
      dtype=float32)

#### 計算損失函數

未經過訓練的模型，給出的機率值接近隨機(1/10)，因此初始損失應該接近

```
-tf.math.log(1/10) ~= 2.3
```

<tf.Tensor: shape=(), dtype=float32, numpy=2.3025851>

##### 使用稀疏分類交叉熵

2.185648

#### 編譯模型

#### 訓練並評估模型

##### 模型訓練

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2925 - accuracy: 0.9160
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1414 - accuracy: 0.9580
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1066 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0876 - accuracy: 0.9733
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0742 - accuracy: 0.9768


##### 模型評估

313/313 - 0s - loss: 0.0766 - accuracy: 0.9773 - 279ms/epoch - 890us/step


[0.07660085707902908, 0.9772999882698059]

##### 建立機率模型

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.9685349e-08, 4.6580761e-10, 4.1183976e-06, 2.7051245e-05,
        1.7616901e-11, 2.5620553e-08, 4.4670671e-14, 9.9996841e-01,
        1.0457931e-08, 3.0099375e-07],
       [5.6043397e-08, 1.8908994e-06, 9.9997544e-01, 1.3402547e-05,
        5.4507765e-13, 9.1772035e-06, 4.0441684e-08, 2.4756091e-12,
        1.7335766e-07, 9.7281749e-12],
       [2.1626022e-08, 9.9910372e-01, 3.5906007e-05, 6.1723372e-06,
        1.9939773e-05, 2.2837387e-06, 2.5395175e-06, 6.9588848e-04,
        1.3338307e-04, 1.6159382e-07],
       [9.9961877e-01, 1.0496628e-09, 3.3688135e-04, 2.1267233e-06,
        7.1936137e-07, 1.4009641e-05, 4.2709266e-06, 1.1332496e-05,
        8.4861327e-08, 1.1701363e-05],
       [5.5400698e-05, 4.9934716e-08, 3.4419077e-06, 1.1753368e-07,
        9.9646264e-01, 1.1198007e-06, 2.9156763e-06, 7.3869531e-05,
        1.8235329e-06, 3.3985446e-03]], dtype=float32)>

###### 印出標準答案

array([7, 2, 1, 0, 4], dtype=uint8)

###### 印出預測結果

array([7, 2, 1, 0, 4])